/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.Font;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mao
 */
public class Home extends javax.swing.JFrame implements Runnable{

    Thread hilo;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        hilo = new Thread(this);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_time = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_sponsor_runner = new javax.swing.JButton();
        btn_find_out_more = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marathon Skills 2015");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lbl_time.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setText("0d days 0h hours 0m minutes 0s seconds until to race starts!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lbl_time)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_time)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MARATHON SKILLS 2015");

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bogotá, Colombia");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Octubre 2015");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_sponsor_runner.setBackground(new java.awt.Color(255, 255, 255));
        btn_sponsor_runner.setForeground(new java.awt.Color(0, 0, 0));
        btn_sponsor_runner.setText("I want to sponsor a runner");
        btn_sponsor_runner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sponsor_runner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sponsor_runnerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sponsor_runnerMouseEntered(evt);
            }
        });
        btn_sponsor_runner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sponsor_runnerActionPerformed(evt);
            }
        });

        btn_find_out_more.setBackground(new java.awt.Color(255, 255, 255));
        btn_find_out_more.setForeground(new java.awt.Color(0, 0, 0));
        btn_find_out_more.setText("I want to find out more");
        btn_find_out_more.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_find_out_more.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_find_out_moreMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_find_out_moreMouseEntered(evt);
            }
        });
        btn_find_out_more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_out_moreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_find_out_more, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sponsor_runner, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_sponsor_runner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_find_out_more, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sponsor_runnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sponsor_runnerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_sponsor_runnerActionPerformed

    private void btn_find_out_moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_out_moreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_find_out_moreActionPerformed

    private void btn_sponsor_runnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sponsor_runnerMouseEntered
        // TODO add your handling code here:
        btn_sponsor_runner.setBackground(new Color(153,153,153));
        btn_sponsor_runner.setForeground(new Color(10,10,10));
        btn_sponsor_runner.setFont(new Font("Dialog", Font.BOLD, 12));
    }//GEN-LAST:event_btn_sponsor_runnerMouseEntered

    private void btn_find_out_moreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_find_out_moreMouseEntered
        // TODO add your handling code here:
        btn_find_out_more.setBackground(new Color(153,153,153));
        btn_find_out_more.setForeground(new Color(10,10,10));
        btn_find_out_more.setFont(new Font("Dialog", Font.BOLD, 12));
    }//GEN-LAST:event_btn_find_out_moreMouseEntered

    private void btn_sponsor_runnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sponsor_runnerMouseExited
        // TODO add your handling code here:
        btn_sponsor_runner.setBackground(Color.white);
        btn_sponsor_runner.setForeground(Color.black);
        btn_sponsor_runner.setFont(new Font("Dialog", Font.PLAIN, 12));
    }//GEN-LAST:event_btn_sponsor_runnerMouseExited

    private void btn_find_out_moreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_find_out_moreMouseExited
        // TODO add your handling code here:
        btn_find_out_more.setBackground(Color.white);
        btn_find_out_more.setForeground(Color.black);
        btn_find_out_more.setFont(new Font("Dialog", Font.PLAIN, 12));
    }//GEN-LAST:event_btn_find_out_moreMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_find_out_more;
    private javax.swing.JButton btn_sponsor_runner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_time;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Calendar future_time = Calendar.getInstance();
        future_time.set(2015, Calendar.NOVEMBER, 23, 6, 0, 0);
        long future_time_in_miliseconds = future_time.getTimeInMillis();
        
        String txt_time = lbl_time.getText();
        
        while(true){
            Calendar current_time = Calendar.getInstance();
            
            long current_time_in_miliseconds = current_time.getTimeInMillis();
            long diff_miliseconds = future_time_in_miliseconds - current_time_in_miliseconds;
            
            int days = (int) (diff_miliseconds)  / ( 1000 * 60 * 60 * 24);
            diff_miliseconds = diff_miliseconds - (days * (1000 * 60 * 60 * 24));
            int hours = (int) (diff_miliseconds) / (1000 * 60 * 60);
            diff_miliseconds = diff_miliseconds - (hours * (1000 * 60 * 60));
            int minutes = (int) diff_miliseconds / (1000 * 60);
            diff_miliseconds = diff_miliseconds - (minutes * (1000 * 60));
            int seconds = (int) diff_miliseconds / (1000);
            
            String text = "";
            
            if(seconds < 10)
                text = txt_time.replace("0d", "0"+days).replace("0h", "0"+hours).replace("0m", "0"+minutes).replace("0s", "0"+seconds);
            else
                text = txt_time.replace("0d", ""+days).replace("0h", ""+hours).replace("0m", ""+minutes).replace("0s", ""+seconds);  
       
            lbl_time.setText(text);
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
