package Views;

import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import marathon.Queries;
import marathon.Runner;
import marathon.Timer;

/**
 * @author Mao
 */
public class Sponsor_a_Runner extends javax.swing.JFrame {
    
    Queries q;
    DefaultComboBoxModel model;
    Runner runner;
    
    /**
     * Creates new form Sponsor_a_Runner
     */
    public Sponsor_a_Runner() {
        initComponents();
        
        /* jDialog */
        jd_charity.setSize(417, 390);
        jd_charity.setLocationRelativeTo(this);
        jd_charity.setTitle("Data Charity");
        jd_charity.setResizable(false);
        
        /* jTextArea */
        jta_description.setLineWrap(true);
        
        SpinnerNumberModel smcvc = new SpinnerNumberModel();
        SpinnerNumberModel smed = new SpinnerNumberModel();
        SpinnerNumberModel smey = new SpinnerNumberModel();
        
        /* Models Spiners */
        smcvc.setValue(0);
        smcvc.setMinimum(0);
        smcvc.setMaximum(999);
        smed.setMinimum(1);
        smed.setValue(1);
        smed.setMaximum(12);
        smey.setMinimum(2016);
        smey.setValue(2016);
        smey.setMaximum(2020);
        
        spi_cvc.setModel(smcvc);
        spi_expire_day.setModel(smed);
        spi_expire_year.setModel(smey);
        
        Timer t  = new Timer(lbl_time);
        
        q = new Queries();
        model = new DefaultComboBoxModel();
        
        ResultSet data = q.get_Runners();
        int number_runners = q.get_Number_Runners();
        
        int num_users = 0;
        
        try {
            model.removeAllElements();
            model.addElement("Select Runner");
            
            while(data.next()){
                model.addElement(new Runner(data.getInt("RunnerId"), data.getString("FirstName"), data.getString("LastName"), data.getString("BibNumber"), data.getString("CountryCode"), data.getInt("CharityId"), data.getInt("RegistrationId")));
            }
            
            jcb_runner.setModel(model);
            jcb_runner.setToolTipText("Number Runners: "+ num_users);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_charity = new javax.swing.JDialog();
        lbl_nameCharity = new javax.swing.JLabel();
        lbl_logoCharity = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_description = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nameSponsor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcb_runner = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        txt_name_card = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_number_card = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spi_expire_year = new javax.swing.JSpinner();
        spi_expire_day = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spi_cvc = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_information_charity = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_number_cash = new javax.swing.JLabel();
        btn_less = new javax.swing.JButton();
        btn_more = new javax.swing.JButton();
        btn_pay_now = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        txt_amount = new javax.swing.JTextField();

        lbl_nameCharity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_nameCharity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nameCharity.setText("Name Charity");

        lbl_logoCharity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jta_description.setEditable(false);
        jta_description.setColumns(20);
        jta_description.setRows(5);
        jScrollPane1.setViewportView(jta_description);

        javax.swing.GroupLayout jd_charityLayout = new javax.swing.GroupLayout(jd_charity.getContentPane());
        jd_charity.getContentPane().setLayout(jd_charityLayout);
        jd_charityLayout.setHorizontalGroup(
            jd_charityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_charityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_charityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_logoCharity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_nameCharity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_charityLayout.setVerticalGroup(
            jd_charityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_charityLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_nameCharity)
                .addGap(18, 18, 18)
                .addComponent(lbl_logoCharity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sponsor a Runner");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MARATHON SKILLS 2016");

        btn_back.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lbl_time.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_time.setText("0d days 0h hours 0m minutes 0s seconds until to race starts!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_time)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sponsor a Runner");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please choose the runner you would like to sponsor and the amount you would like");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("the sponsor them for. Thank you for your support of the runners and their charities!");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sponsorship Details");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Your Name");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Runner");

        jcb_runner.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jcb_runner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mathie (USA)" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Name Card");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Credit Card #");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Expire date");

        spi_expire_year.setValue(2015);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("CVC");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_number_card, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_name_card)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spi_cvc, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(spi_expire_day))
                                .addGap(18, 18, 18)
                                .addComponent(spi_expire_year, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_runner, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_nameSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nameSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcb_runner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_name_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_number_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spi_expire_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spi_expire_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spi_cvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Charity");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Save The Cats fund");

        lbl_information_charity.setForeground(new java.awt.Color(182, 182, 7));
        lbl_information_charity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_information_charity.setText("?");
        lbl_information_charity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_information_charity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_information_charity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_information_charityMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Amount to Donate");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 54)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("$");

        lbl_number_cash.setFont(new java.awt.Font("Dialog", 0, 54)); // NOI18N
        lbl_number_cash.setForeground(new java.awt.Color(153, 153, 153));
        lbl_number_cash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_number_cash.setText("0");

        btn_less.setText("-");
        btn_less.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lessActionPerformed(evt);
            }
        });

        btn_more.setText("+");
        btn_more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moreActionPerformed(evt);
            }
        });

        btn_pay_now.setText("Pay Now");
        btn_pay_now.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pay_nowActionPerformed(evt);
            }
        });

        btn_reset.setText("Cancel");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        txt_amount.setToolTipText("Presione \"Enter\" para ingresar la cantidad");
        txt_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_amountKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_information_charity, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_number_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_less)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(btn_pay_now)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_reset))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addGap(58, 58, 58)
                                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_more))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_information_charity))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_number_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_less)
                    .addComponent(btn_more)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pay_now)
                    .addComponent(btn_reset))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_lessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lessActionPerformed
        // TODO add your handling code here:
        int amount = Integer.parseInt(lbl_number_cash.getText());
        
        if(amount == 0 || amount < 10){
            return;
        }else{
            lbl_number_cash.setText(""+(amount - 10));
        }
    }//GEN-LAST:event_btn_lessActionPerformed

    private void btn_moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moreActionPerformed
        // TODO add your handling code here:
        int amount = Integer.parseInt(lbl_number_cash.getText());
        lbl_number_cash.setText(""+(amount + 10));
    }//GEN-LAST:event_btn_moreActionPerformed

    private void txt_amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            if(Integer.parseInt(txt_amount.getText()) < 0){
                JOptionPane.showMessageDialog(this, "Write Positive Values","Error",JOptionPane.ERROR_MESSAGE);
                txt_amount.setText("");
            }else{
                int amount = Integer.parseInt(lbl_number_cash.getText());
                try {
                    lbl_number_cash.setText(""+(amount + Integer.parseInt(txt_amount.getText())));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Write Only Numbers","Error",JOptionPane.ERROR_MESSAGE);
                }
                txt_amount.setText("");
            }
        }
    }//GEN-LAST:event_txt_amountKeyPressed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_pay_nowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pay_nowActionPerformed
        // TODO add your handling code here:
        String name = txt_nameSponsor.getText();
        String name_card = txt_name_card.getText();
        long number_card = 0;
        int expire_day = 0;
        int expire_year = 0;
        int cvc = 0;
        int mount = Integer.parseInt(lbl_number_cash.getText());
        
        Calendar time = Calendar.getInstance();
        int year = Integer.parseInt(time.getTime().toString().split(" ")[5]);
        
        try{
            number_card = Long.parseLong(txt_number_card.getText());
            expire_day = Integer.parseInt(spi_expire_day.getValue().toString());
            expire_year = Integer.parseInt(spi_expire_year.getValue().toString());
            cvc = Integer.parseInt(spi_cvc.getValue().toString());
        }catch(Exception e){
            System.out.println(e);
        }
        
        if("".equals(name)){
            message(this, "The Name is empty" ,"Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
            txt_nameSponsor.requestFocus();
        }else if(jcb_runner.getSelectedIndex() == 0){
            message(this, "Select one Runner","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            jcb_runner.requestFocus();
        }else if("".equals(name_card)){
            message(this, "The Name Card is empty","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            txt_name_card.requestFocus();
        }else if("".equals(txt_number_card.getText())){
            message(this, "The Number Card is empty","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            txt_number_card.requestFocus();
        }else if(txt_number_card.getText().length() != 16){
            message(this, "The Number Card must have 16 numbers","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            txt_number_card.requestFocus();
        }else if(expire_year < year){
            message(this, "The year must be major that this year","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            spi_expire_year.requestFocus();
        }else if("0".equals(spi_cvc.getValue().toString()) || Integer.parseInt(spi_cvc.getValue().toString()) < 100){
            message(this, "The Number CVC isn't valid","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            spi_cvc.requestFocus();
        }else if(mount == 0){
            message(this, "The amount to donate can't be 0","Marathon Skills 2016",JOptionPane.WARNING_MESSAGE);
            txt_amount.requestFocus();
        }else{
            runner = (Runner) jcb_runner.getSelectedItem();
            boolean response = q.set_Sponsorship(name.toUpperCase(), runner.getRegistrationId(), mount);
            
            if(response){
                Sponsorship_Confirmation sc = new Sponsorship_Confirmation();
                this.setVisible(false);
                sc.lbl_number_cash.setText(""+mount);
                sc.lbl_runnerName.setText(jcb_runner.getSelectedItem().toString());
                sc.setVisible(true);
            }else{
                message(this, "Error conection database", "Marathon Skills 2016", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_pay_nowActionPerformed

    private void lbl_information_charityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_information_charityMouseClicked
        // TODO add your handling code here:
        if(jcb_runner.getSelectedIndex() == 0){
            message(this, "Select first one runner", "Marathon Skills 2016", JOptionPane.WARNING_MESSAGE);
        }else{
            runner = (Runner) jcb_runner.getSelectedItem();
            
            String[] dataCharity;
            dataCharity = q.get_Data_Charity(runner.getIdCharity());
            
            lbl_nameCharity.setText(dataCharity[0]);
            jta_description.setText(dataCharity[1]);
            lbl_logoCharity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+dataCharity[2])));
            
            // show the dialog
            jd_charity.setVisible(true);
        }
    }//GEN-LAST:event_lbl_information_charityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sponsor_a_Runner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sponsor_a_Runner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sponsor_a_Runner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sponsor_a_Runner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sponsor_a_Runner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_less;
    private javax.swing.JButton btn_more;
    private javax.swing.JButton btn_pay_now;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_runner;
    private javax.swing.JDialog jd_charity;
    private javax.swing.JTextArea jta_description;
    private javax.swing.JLabel lbl_information_charity;
    private javax.swing.JLabel lbl_logoCharity;
    private javax.swing.JLabel lbl_nameCharity;
    private javax.swing.JLabel lbl_number_cash;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JSpinner spi_cvc;
    private javax.swing.JSpinner spi_expire_day;
    private javax.swing.JSpinner spi_expire_year;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_nameSponsor;
    private javax.swing.JTextField txt_name_card;
    private javax.swing.JTextField txt_number_card;
    // End of variables declaration//GEN-END:variables

    private void message(JFrame form, String message, String title, int icon) {
        JOptionPane.showMessageDialog(form, message, title, icon);
    }
}
